# -*- coding: utf-8 -*-
"""
/***************************************************************************
 maszekplugin
                                 A QGIS plugin
 maszekplugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-02-26
        copyright            : (C) 2024 by Bator Koncz & Pal Szabo
        email                : zabop@protonmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = "Bator Koncz & Pal Szabo"
__date__ = "2024-02-26"
__copyright__ = "(C) 2024 by Bator Koncz & Pal Szabo"


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load maszekplugin class from file maszekplugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .maszekplugin_processing import maszekpluginPlugin

    return maszekpluginPlugin()
